-- ============================================================================
-- Add 7 services under the "Tumor Surgery" category with starter bilingual
-- content. Content-safe: only INSERTs new rows; skips any slug that already
-- exists. Add images and refine text afterwards in Admin - Services.
-- Run once in the Supabase SQL Editor.
-- ============================================================================

insert into public.services
  (slug, slug_ar, slug_en, category_id, is_published, show_on_home, sort_order, glyph,
   tag_ar, tag_en, title_ar, title_en, short_desc_ar, short_desc_en,
   hero_sub_ar, hero_sub_en, intro_ar, intro_en, sections, benefits, faq,
   meta_title_ar, meta_title_en, meta_desc_ar, meta_desc_en)
values
-- 1) استئصال الأورام الليفية -------------------------------------------------
('fibroid-removal', 'استئصال-الأورام-الليفية', 'fibroid-removal',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+1, '❀',
 'جراحة أورام', 'Tumor surgery', 'استئصال الأورام الليفية', 'Fibroid Removal',
 'استئصال الأورام الليفية بأمان مع الحفاظ على الرحم والقدرة على الإنجاب كلما أمكن.',
 'Safe removal of uterine fibroids while preserving the uterus and fertility whenever possible.',
 'استئصال دقيق للأورام الليفية مع الحفاظ على الرحم كلما أمكن.',
 'Precise fibroid removal while preserving the uterus whenever possible.',
 'الأورام الليفية أورام حميدة شائعة في الرحم قد تسبب نزيفًا وآلامًا أو تؤثر على الخصوبة. نقدم استئصالًا دقيقًا للورم مع الحفاظ على الرحم كلما كان ذلك ممكنًا.',
 'Uterine fibroids are common benign tumors that may cause bleeding, pain, or affect fertility. We provide precise removal while preserving the uterus whenever possible.',
 '[{"heading_ar":"متى يكون التدخل الجراحي ضروريًا؟","heading_en":"When is surgery needed?","body_ar":"يصبح التدخل ضروريًا مع النزيف الغزير أو الآلام المستمرة أو الضغط على الأعضاء المجاورة أو تأثير الورم على الخصوبة والحمل.","body_en":"Surgery becomes necessary with heavy bleeding, persistent pain, pressure on nearby organs, or an effect on fertility and pregnancy."},{"heading_ar":"الحفاظ على الرحم","heading_en":"Preserving the uterus","body_ar":"هدفنا في الحالات المناسبة هو إزالة الورم مع الحفاظ على الرحم لتبقى فرص الإنجاب قائمة.","body_en":"Our goal in suitable cases is to remove the fibroid while keeping the uterus so fertility remains possible."}]'::jsonb,
 '[{"ar":"تخفيف النزيف والآلام","en":"Relief from bleeding and pain"},{"ar":"الحفاظ على الرحم والخصوبة","en":"Preserving the uterus and fertility"},{"ar":"خطة علاج مخصصة لكل حالة","en":"A tailored plan for each case"}]'::jsonb,
 '[{"q_ar":"هل يمكنني الإنجاب بعد العملية؟","q_en":"Can I conceive after surgery?","a_ar":"في الحالات المناسبة نحافظ على الرحم لتظل فرص الإنجاب قائمة.","a_en":"In suitable cases we preserve the uterus so fertility remains possible."},{"q_ar":"هل كل الأورام الليفية تحتاج جراحة؟","q_en":"Do all fibroids need surgery?","a_ar":"لا، كثير منها لا يسبب أعراضًا. الجراحة للحالات التي تسبب مشاكل فقط.","a_en":"No, many cause no symptoms. Surgery is only for those causing problems."}]'::jsonb,
 'استئصال الأورام الليفية | د. أحمد مرزوق', 'Fibroid Removal | Dr. Ahmed Marzouk',
 'استئصال الأورام الليفية مع الحفاظ على الرحم والقدرة على الإنجاب مع د. أحمد مرزوق.',
 'Uterine fibroid removal while preserving the uterus and fertility with Dr. Ahmed Marzouk.'),

-- 2) استئصال الأورام الليفية بالمنظار ----------------------------------------
('laparoscopic-fibroid-removal', 'استئصال-الأورام-الليفية-بالمنظار', 'laparoscopic-fibroid-removal',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+2, '✚',
 'جراحة أورام', 'Tumor surgery', 'استئصال الأورام الليفية بالمنظار', 'Laparoscopic Fibroid Removal',
 'إزالة الأورام الليفية بالمنظار الجراحي بجروح صغيرة وتعافٍ أسرع.',
 'Removing fibroids by laparoscopy through tiny incisions with faster recovery.',
 'جراحة منظار دقيقة بجروح صغيرة وألم أقل وتعافٍ أسرع.',
 'Precise keyhole surgery with tiny incisions, less pain and faster recovery.',
 'يتيح المنظار الجراحي استئصال الأورام الليفية من خلال جروح صغيرة جدًا، مما يقلل الألم وفترة النقاهة مقارنة بالجراحة التقليدية.',
 'Laparoscopy allows fibroid removal through very small incisions, reducing pain and recovery time compared to open surgery.',
 '[{"heading_ar":"مزايا المنظار","heading_en":"Benefits of laparoscopy","body_ar":"جروح صغيرة، ألم أقل، إقامة أقصر بالمستشفى، وعودة أسرع للحياة الطبيعية مع ندبات أقل.","body_en":"Small incisions, less pain, a shorter hospital stay, and a faster return to normal life with minimal scarring."},{"heading_ar":"لمن يناسب؟","heading_en":"Who is it suitable for?","body_ar":"يحدد الطبيب مدى ملاءمة المنظار حسب حجم الورم وعدده وموضعه بعد تقييم دقيق.","body_en":"The surgeon determines suitability based on the size, number and location of the fibroids after careful assessment."}]'::jsonb,
 '[{"ar":"جروح صغيرة وندبات أقل","en":"Small incisions, minimal scarring"},{"ar":"ألم أقل وتعافٍ أسرع","en":"Less pain and faster recovery"},{"ar":"إقامة أقصر بالمستشفى","en":"Shorter hospital stay"}]'::jsonb,
 '[{"q_ar":"هل المنظار مناسب لكل الأورام؟","q_en":"Is laparoscopy suitable for all fibroids?","a_ar":"يعتمد ذلك على حجم الورم وموضعه؛ نقيّم كل حالة لاختيار الأنسب.","a_en":"It depends on the size and location; we assess each case to choose the best approach."},{"q_ar":"كم تستغرق فترة التعافي؟","q_en":"How long is recovery?","a_ar":"عادة أسرع من الجراحة المفتوحة، مع عودة تدريجية خلال أيام إلى أسابيع قليلة.","a_en":"Usually faster than open surgery, with a gradual return over days to a few weeks."}]'::jsonb,
 'استئصال الأورام الليفية بالمنظار | د. أحمد مرزوق', 'Laparoscopic Fibroid Removal | Dr. Ahmed Marzouk',
 'استئصال الأورام الليفية بالمنظار بجروح صغيرة وتعافٍ أسرع مع د. أحمد مرزوق.',
 'Laparoscopic fibroid removal through tiny incisions with faster recovery with Dr. Ahmed Marzouk.'),

-- 3) بطانة الرحم المهاجرة -----------------------------------------------------
('endometriosis-surgery', 'علاج-بطانة-الرحم-المهاجرة', 'endometriosis-surgery',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+3, '✿',
 'جراحة أورام', 'Tumor surgery', 'بطانة الرحم المهاجرة', 'Endometriosis',
 'تشخيص دقيق وعلاج جراحي لبطانة الرحم المهاجرة للتخلص من الألم المزمن.',
 'Precise diagnosis and surgical treatment of endometriosis to relieve chronic pain.',
 'تشخيص وعلاج متخصص لبطانة الرحم المهاجرة لاستعادة جودة حياتك.',
 'Specialized diagnosis and treatment of endometriosis to restore your quality of life.',
 'بطانة الرحم المهاجرة حالة مزمنة كثيرًا ما يتأخر تشخيصها. نقدم تشخيصًا دقيقًا وعلاجًا جراحيًا عند الحاجة لإزالة البؤر وتخفيف الألم وتحسين فرص الإنجاب.',
 'Endometriosis is a chronic condition whose diagnosis is often delayed. We provide accurate diagnosis and surgical treatment when needed to remove lesions, relieve pain and improve fertility.',
 '[{"heading_ar":"لماذا يتأخر التشخيص؟","heading_en":"Why is diagnosis delayed?","body_ar":"غالبًا ما تُنسب الأعراض خطأً لآلام الدورة الطبيعية، فيتأخر التشخيص سنوات. الخبرة المتخصصة تُحدث فرقًا كبيرًا.","body_en":"Symptoms are often wrongly attributed to normal period pain, delaying diagnosis for years. Specialized experience makes a big difference."},{"heading_ar":"العلاج الجراحي","heading_en":"Surgical treatment","body_ar":"عند الحاجة نزيل البؤر والالتصاقات بالمنظار مع الحفاظ على الأعضاء لتخفيف الألم وتحسين الخصوبة.","body_en":"When needed we remove lesions and adhesions laparoscopically while preserving the organs to relieve pain and improve fertility."}]'::jsonb,
 '[{"ar":"تشخيص دقيق ومبكر","en":"Accurate, early diagnosis"},{"ar":"تخفيف الألم المزمن","en":"Relief from chronic pain"},{"ar":"تحسين فرص الإنجاب","en":"Improved fertility prospects"}]'::jsonb,
 '[{"q_ar":"ما أبرز الأعراض؟","q_en":"What are the main symptoms?","a_ar":"آلام الدورة الشديدة وآلام الحوض المزمنة وأحيانًا صعوبة الحمل.","a_en":"Severe period pain, chronic pelvic pain, and sometimes difficulty conceiving."},{"q_ar":"هل تحتاج دائمًا جراحة؟","q_en":"Does it always need surgery?","a_ar":"لا، تُعالج كثير من الحالات دوائيًا؛ الجراحة للحالات المتقدمة أو المؤثرة على الخصوبة.","a_en":"No, many cases are treated with medication; surgery is for advanced cases or those affecting fertility."}]'::jsonb,
 'علاج بطانة الرحم المهاجرة | د. أحمد مرزوق', 'Endometriosis Treatment | Dr. Ahmed Marzouk',
 'تشخيص وعلاج بطانة الرحم المهاجرة جراحيًا للتخلص من الألم المزمن مع د. أحمد مرزوق.',
 'Diagnosis and surgical treatment of endometriosis to relieve chronic pain with Dr. Ahmed Marzouk.'),

-- 4) استئصال الرحم بالمنظار ---------------------------------------------------
('laparoscopic-hysterectomy', 'استئصال-الرحم-بالمنظار', 'laparoscopic-hysterectomy',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+4, '⚕',
 'جراحة أورام', 'Tumor surgery', 'استئصال الرحم بالمنظار', 'Laparoscopic Hysterectomy',
 'استئصال الرحم بالمنظار عند الحاجة الطبية بجروح صغيرة وتعافٍ أسرع.',
 'Laparoscopic hysterectomy when medically needed, with small incisions and faster recovery.',
 'جراحة منظار دقيقة عند الحاجة لاستئصال الرحم بأمان وراحة.',
 'Precise keyhole surgery when hysterectomy is needed, done safely and comfortably.',
 'في بعض الحالات المرضية يكون استئصال الرحم هو الخيار الأنسب. نجريه بالمنظار كلما أمكن لتقليل الألم وفترة النقاهة.',
 'In some conditions a hysterectomy is the most suitable option. We perform it laparoscopically whenever possible to reduce pain and recovery time.',
 '[{"heading_ar":"متى يُنصح به؟","heading_en":"When is it advised?","body_ar":"يُنصح به في حالات مثل الأورام الكبيرة أو النزيف المزمن الذي لا يستجيب للعلاج أو بعض أمراض الرحم، بعد مناقشة كل البدائل.","body_en":"It is advised for cases such as large tumors, chronic bleeding unresponsive to treatment, or certain uterine conditions, after discussing all alternatives."},{"heading_ar":"لماذا المنظار؟","heading_en":"Why laparoscopy?","body_ar":"يوفر جروحًا أصغر وألمًا أقل وإقامة أقصر وعودة أسرع للحياة الطبيعية.","body_en":"It offers smaller incisions, less pain, a shorter stay and a faster return to normal life."}]'::jsonb,
 '[{"ar":"جروح صغيرة وألم أقل","en":"Small incisions and less pain"},{"ar":"إقامة أقصر بالمستشفى","en":"Shorter hospital stay"},{"ar":"تعافٍ أسرع","en":"Faster recovery"}]'::jsonb,
 '[{"q_ar":"هل يوجد بديل عن استئصال الرحم؟","q_en":"Is there an alternative to hysterectomy?","a_ar":"نناقش دائمًا كل البدائل الممكنة، ولا نلجأ للاستئصال إلا عند الضرورة الطبية.","a_en":"We always discuss every possible alternative and only proceed when medically necessary."},{"q_ar":"كم تستغرق النقاهة؟","q_en":"How long is recovery?","a_ar":"عادة أسرع مع المنظار، مع عودة تدريجية للنشاط خلال أسابيع قليلة.","a_en":"Usually faster with laparoscopy, with a gradual return to activity over a few weeks."}]'::jsonb,
 'استئصال الرحم بالمنظار | د. أحمد مرزوق', 'Laparoscopic Hysterectomy | Dr. Ahmed Marzouk',
 'استئصال الرحم بالمنظار عند الحاجة بجروح صغيرة وتعافٍ أسرع مع د. أحمد مرزوق.',
 'Laparoscopic hysterectomy when needed, with small incisions and faster recovery with Dr. Ahmed Marzouk.'),

-- 5) استئصال أكياس من على المبيض ---------------------------------------------
('ovarian-cyst-removal', 'استئصال-أكياس-من-على-المبيض', 'ovarian-cyst-removal',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+5, '◈',
 'جراحة أورام', 'Tumor surgery', 'استئصال أكياس المبيض', 'Ovarian Cyst Removal',
 'إزالة أكياس المبيض مع الحفاظ على المبيض ووظيفته والخصوبة كلما أمكن.',
 'Removing ovarian cysts while preserving the ovary, its function and fertility whenever possible.',
 'استئصال دقيق لأكياس المبيض مع الحفاظ على المبيض السليم.',
 'Precise removal of ovarian cysts while preserving the healthy ovary.',
 'أكياس المبيض شائعة وكثير منها يزول تلقائيًا، لكن بعضها يستدعي التدخل الجراحي. نحرص على إزالة الكيس مع الحفاظ على أنسجة المبيض السليمة ووظيفته.',
 'Ovarian cysts are common and many resolve on their own, but some require surgery. We remove the cyst while preserving the healthy ovarian tissue and its function.',
 '[{"heading_ar":"متى يحتاج الكيس لجراحة؟","heading_en":"When does a cyst need surgery?","body_ar":"عند كبر حجمه أو استمراره أو تسببه في آلام أو الاشتباه في طبيعته، نقرر التدخل بعد تقييم دقيق.","body_en":"When it is large, persistent, painful, or its nature is suspicious, we decide on surgery after careful assessment."},{"heading_ar":"الحفاظ على المبيض","heading_en":"Preserving the ovary","body_ar":"نستأصل الكيس مع الحفاظ على أكبر قدر من نسيج المبيض السليم لحماية الخصوبة.","body_en":"We remove the cyst while preserving as much healthy ovarian tissue as possible to protect fertility."}]'::jsonb,
 '[{"ar":"الحفاظ على المبيض والخصوبة","en":"Preserving the ovary and fertility"},{"ar":"تخفيف الألم والأعراض","en":"Relief from pain and symptoms"},{"ar":"تقييم دقيق وآمن","en":"Careful, safe assessment"}]'::jsonb,
 '[{"q_ar":"هل تؤثر العملية على الخصوبة؟","q_en":"Does the surgery affect fertility?","a_ar":"نحرص على الحفاظ على المبيض ووظيفته لتظل الخصوبة محمية قدر الإمكان.","a_en":"We aim to preserve the ovary and its function so fertility stays protected as much as possible."},{"q_ar":"هل كل الأكياس تحتاج جراحة؟","q_en":"Do all cysts need surgery?","a_ar":"لا، كثير منها يزول تلقائيًا؛ نتدخل فقط عند الحاجة.","a_en":"No, many resolve on their own; we operate only when needed."}]'::jsonb,
 'استئصال أكياس المبيض | د. أحمد مرزوق', 'Ovarian Cyst Removal | Dr. Ahmed Marzouk',
 'استئصال أكياس المبيض مع الحفاظ على المبيض والخصوبة مع د. أحمد مرزوق.',
 'Ovarian cyst removal while preserving the ovary and fertility with Dr. Ahmed Marzouk.'),

-- 6) استئصال الأكياس الشوكولاتية ----------------------------------------------
('chocolate-cyst-removal', 'استئصال-الأكياس-الشوكولاتية', 'chocolate-cyst-removal',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+6, '✜',
 'جراحة أورام', 'Tumor surgery', 'استئصال الأكياس الشوكولاتية', 'Chocolate Cyst Removal',
 'إزالة الأكياس الشوكولاتية (بطانة الرحم على المبيض) مع الحفاظ على الخصوبة.',
 'Removing chocolate cysts (ovarian endometriomas) while preserving fertility.',
 'علاج دقيق للأكياس الشوكولاتية مع الحفاظ على المبيض.',
 'Precise treatment of chocolate cysts while preserving the ovary.',
 'الأكياس الشوكولاتية نوع من بطانة الرحم المهاجرة يتكوّن على المبيض وقد يؤثر على الخصوبة. نزيلها بدقة بالمنظار مع الحفاظ على أنسجة المبيض السليمة.',
 'Chocolate cysts are a form of endometriosis that forms on the ovary and can affect fertility. We remove them precisely by laparoscopy while preserving healthy ovarian tissue.',
 '[{"heading_ar":"تأثيرها على الخصوبة","heading_en":"Effect on fertility","body_ar":"قد تؤثر الأكياس الشوكولاتية على مخزون المبيض والخصوبة، لذا نتعامل معها بعناية للحفاظ على أكبر قدر من النسيج السليم.","body_en":"Chocolate cysts may affect ovarian reserve and fertility, so we handle them carefully to preserve as much healthy tissue as possible."},{"heading_ar":"العلاج بالمنظار","heading_en":"Laparoscopic treatment","body_ar":"نزيل الكيس بالمنظار بدقة عالية لتقليل الضرر على المبيض وتحسين النتائج.","body_en":"We remove the cyst laparoscopically with high precision to minimize damage to the ovary and improve outcomes."}]'::jsonb,
 '[{"ar":"الحفاظ على مخزون المبيض","en":"Preserving ovarian reserve"},{"ar":"تخفيف الألم المزمن","en":"Relief from chronic pain"},{"ar":"تحسين فرص الإنجاب","en":"Improved fertility prospects"}]'::jsonb,
 '[{"q_ar":"ما الأكياس الشوكولاتية؟","q_en":"What are chocolate cysts?","a_ar":"أكياس على المبيض ناتجة عن بطانة الرحم المهاجرة وتحتوي على دم قديم داكن.","a_en":"Cysts on the ovary caused by endometriosis, containing old dark blood."},{"q_ar":"هل تتكرر بعد العلاج؟","q_en":"Can they recur after treatment?","a_ar":"قد تتكرر أحيانًا، لذا نضع خطة متابعة فردية لكل حالة.","a_en":"They can sometimes recur, so we set an individual follow-up plan for each case."}]'::jsonb,
 'استئصال الأكياس الشوكولاتية | د. أحمد مرزوق', 'Chocolate Cyst Removal | Dr. Ahmed Marzouk',
 'استئصال الأكياس الشوكولاتية بالمنظار مع الحفاظ على المبيض والخصوبة مع د. أحمد مرزوق.',
 'Laparoscopic chocolate cyst removal while preserving the ovary and fertility with Dr. Ahmed Marzouk.'),

-- 7) فك التصاقات البطن والحوض -------------------------------------------------
('pelvic-adhesiolysis', 'فك-التصاقات-البطن-والحوض', 'pelvic-adhesiolysis',
 (select id from public.service_categories where slug='tumor-surgery'), true, false,
 (select coalesce(max(sort_order),0) from public.services)+7, '⟡',
 'جراحة أورام', 'Tumor surgery', 'فك التصاقات البطن والحوض', 'Abdominal & Pelvic Adhesiolysis',
 'فك التصاقات البطن والحوض بالمنظار لتخفيف الألم وتحسين الخصوبة.',
 'Laparoscopic release of abdominal and pelvic adhesions to relieve pain and improve fertility.',
 'علاج دقيق للالتصاقات لاستعادة الراحة والوظيفة الطبيعية.',
 'Precise treatment of adhesions to restore comfort and normal function.',
 'قد تنشأ الالتصاقات بعد الجراحات أو الالتهابات وتسبب آلامًا مزمنة أو مشاكل في الخصوبة. نفكّها بالمنظار بدقة لاستعادة الحركة الطبيعية للأعضاء.',
 'Adhesions may form after surgery or infection and cause chronic pain or fertility problems. We release them laparoscopically with precision to restore the normal movement of the organs.',
 '[{"heading_ar":"أسباب الالتصاقات","heading_en":"Causes of adhesions","body_ar":"تنشأ غالبًا بعد العمليات الجراحية أو الالتهابات الحوضية أو بطانة الرحم المهاجرة.","body_en":"They usually form after surgery, pelvic infections, or endometriosis."},{"heading_ar":"العلاج بالمنظار","heading_en":"Laparoscopic treatment","body_ar":"نفكّ الالتصاقات بعناية لتخفيف الألم وتحسين فرص الحمل مع تقليل احتمال تكوّنها من جديد.","body_en":"We carefully release the adhesions to relieve pain and improve fertility while reducing the chance of them reforming."}]'::jsonb,
 '[{"ar":"تخفيف الألم المزمن","en":"Relief from chronic pain"},{"ar":"تحسين فرص الإنجاب","en":"Improved fertility prospects"},{"ar":"جراحة دقيقة بالمنظار","en":"Precise laparoscopic surgery"}]'::jsonb,
 '[{"q_ar":"هل تعود الالتصاقات بعد فكها؟","q_en":"Do adhesions return after release?","a_ar":"نستخدم تقنيات دقيقة لتقليل عودتها، مع متابعة فردية لكل حالة.","a_en":"We use precise techniques to reduce recurrence, with individual follow-up for each case."},{"q_ar":"هل تحسّن العملية الخصوبة؟","q_en":"Does the surgery improve fertility?","a_ar":"في كثير من الحالات نعم، خاصة عندما تكون الالتصاقات سبب صعوبة الحمل.","a_en":"In many cases yes, especially when adhesions are the cause of difficulty conceiving."}]'::jsonb,
 'فك التصاقات البطن والحوض | د. أحمد مرزوق', 'Pelvic Adhesiolysis | Dr. Ahmed Marzouk',
 'فك التصاقات البطن والحوض بالمنظار لتخفيف الألم وتحسين الخصوبة مع د. أحمد مرزوق.',
 'Laparoscopic release of abdominal and pelvic adhesions to relieve pain and improve fertility with Dr. Ahmed Marzouk.')

on conflict (slug) do nothing;
