-- Recovery Phase 3b: fill empty/generic SEO fields on the new blogs.
-- meta_description & excerpt derived from each article's OWN opening text
-- (not fabricated); tag from primary_keyword; alt set to the article title
-- (descriptive draft, still flagged for human review). Idempotent by id.
START TRANSACTION;
UPDATE `blog_posts` SET `meta_desc_ar`='التهاب الثدي هي حالة شائعة بين الأمهات الجدد، حيث تصيب  حوالي 1 من كل 10 نساء مرضعات، وهو ينطوي على التهاب أنسجة الثدي وغالبًا ما يكون مصحوبًا بعدوى متوسطة إلى', `meta_desc_en`='Mastitis is a common condition among new mothers, affecting around 1 in 10 breastfeeding women. It involves inflammation of the breast tissue and is often…', `excerpt_ar`='التهاب الثدي هي حالة شائعة بين الأمهات الجدد، حيث تصيب  حوالي 1 من كل 10 نساء مرضعات، وهو ينطوي على التهاب أنسجة الثدي وغالبًا ما يكون مصحوبًا بعدوى متوسطة…', `excerpt_en`='Mastitis is a common condition among new mothers, affecting around 1 in 10 breastfeeding women. It involves inflammation of the breast tissue and is often…', `tag_ar`='هل التهاب الثدي خطير', `tag_en`=NULL, `image_alt_ar`='أسباب التهاب الثدي وطرق علاجه', `image_alt_en`='Causes of mastitis and methods of treatment' WHERE `id`='96dd8880-1d95-52c2-b0c5-af844faab788';
UPDATE `blog_posts` SET `meta_desc_ar`='الحمل الكيميائي هو الحمل الذي ينتهي مبكرًا بسبب حدوث إجهاض خلال الأسابيع الخمسة الأولى من الحمل. في الحمل الكيميائي، يتوقف الجنين عن النمو بعد تكونه في بطانة ال', `meta_desc_en`='A chemical pregnancy is a pregnancy that ends prematurely due to a miscarriage within the first five weeks of pregnancy. In a chemical pregnancy, the foetus…', `excerpt_ar`='الحمل الكيميائي هو الحمل الذي ينتهي مبكرًا بسبب حدوث إجهاض خلال الأسابيع الخمسة الأولى من الحمل. في الحمل الكيميائي، يتوقف الجنين عن النمو بعد تكونه وانغماسه…', `excerpt_en`='A chemical pregnancy is a pregnancy that ends prematurely due to a miscarriage within the first five weeks of pregnancy. In a chemical pregnancy, the foetus…', `tag_ar`='الحمل الكيميائي', `tag_en`=NULL, `image_alt_ar`='تعرف على كل ما يخص الحمل الكيميائي', `image_alt_en`='Find out all about chemical pregnancy' WHERE `id`='3440ab6d-44b5-5b8c-8573-3de70f652db3';
UPDATE `blog_posts` SET `meta_desc_ar`='انقطاع الطمث هو نهاية الدورة الشهرية للمرأة، ويشمل جميع التغييرات التي تمر بها قبل أو بعد توقف الدورة الشهرية، كما يشير إلى نهاية سنوات الإنجاب', `meta_desc_en`='Menopause is the end of a woman\'s menstrual cycle, and it includes all the changes she experiences before or after menstruation stops. It also indicates the…', `excerpt_ar`='انقطاع الطمث هو نهاية الدورة الشهرية للمرأة، ويشمل جميع التغييرات التي تمر بها قبل أو بعد توقف الدورة الشهرية، كما يشير إلى نهاية سنوات الإنجاب.', `excerpt_en`='Menopause is the end of a woman\'s menstrual cycle, and it includes all the changes she experiences before or after menstruation stops. It also indicates the…', `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='انقطاع الطمث', `image_alt_en`='Menopause' WHERE `id`='0e1eb956-fd14-56f0-9fca-d851b00d6ff8';
UPDATE `blog_posts` SET `meta_desc_ar`='الولادة لها أثر كبير على جسدك. قد تشعرين بالعديد من الأحاسيس المختلفة في الأيام والأسابيع التي تلي ولادة طفلك. من الشائع التساؤل عما إذا كانت الأعراض طبيعية…', `meta_desc_en`='Childbirth has a huge impact on your body. You may experience many different sensations in the days and weeks after your baby\'s birth. It is common to ask…', `excerpt_ar`='الولادة لها أثر كبير على جسدك. قد تشعرين بالعديد من الأحاسيس المختلفة في الأيام والأسابيع التي تلي ولادة طفلك. من الشائع التساؤل عما إذا كانت الأعراض طبيعية…', `excerpt_en`='Childbirth has a huge impact on your body. You may experience many different sensations in the days and weeks after your baby\'s birth. It is common to ask…', `tag_ar`='حمى النفاس', `tag_en`=NULL, `image_alt_ar`='الحمى بعد الولادة', `image_alt_en`='Postpartum fever' WHERE `id`='c82fe0e4-efab-589c-b855-a841c7313ae8';
UPDATE `blog_posts` SET `meta_desc_ar`='عندما يبدأ ارتفاع ضغط الدم في التأثير على الأعضاء الأخرى، مثل الكلى أو الكبد، يُسمى تسمم الحمل. علامة أخرى على تسمم الحمل هي وجود الكثير من البروتين في البول', `meta_desc_en`='Blood pressure is a vital sign that we pay great attention to throughout pregnancy, as your body goes through many changes. Among these changes are those…', `excerpt_ar`='يعد ضغط الدم من العلامات الحيوية التي نوليها اهتمامًا كبيرًا طوال فترة الحمل، حيث يمر جسمك بالعديد من التغييرات أثناء الحمل، سواء من الداخل أو الخارج. من ضمن…', `excerpt_en`='Blood pressure is a vital sign that we pay great attention to throughout pregnancy, as your body goes through many changes. Among these changes are those…', `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='ارتفاع ضغط الدم وتسمم الحمل', `image_alt_en`='Hypertension and Preeclampsia' WHERE `id`='a7eef3d3-024e-5baf-8927-767d329a4573';
UPDATE `blog_posts` SET `meta_desc_ar`='القيء المستعصي هو غثيان وقيء شديدين ومستمرين أثناء الحمل. يمكن أن يؤدي القيء المستعصي إلى جفاف، فقدان الوزن، وغيرهما. يبدأ القيء المستعصي بين 4 إلى 8 أسابيع من', `meta_desc_en`='Intractable vomiting is severe and persistent nausea and vomiting during pregnancy. Intractable vomiting can lead to dehydration, weight loss, etc…', `excerpt_ar`='القيء المستعصي هو غثيان وقيء شديدين ومستمرين أثناء الحمل. يمكن أن يؤدي القيء المستعصي إلى جفاف، فقدان الوزن، وغيرهما. يبدأ القيء المستعصي بين 4 إلى 8 أسابيع…', `excerpt_en`='Intractable vomiting is severe and persistent nausea and vomiting during pregnancy. Intractable vomiting can lead to dehydration, weight loss, etc…', `tag_ar`='أسباب القيء المستعصي للحامل', `tag_en`=NULL, `image_alt_ar`='طرق التحكم في القيء المستعصي أثناء الحمل', `image_alt_en`='Ways to control intractable vomiting during pregnancy' WHERE `id`='4ac6c686-9367-504b-8281-8e79598b61b3';
UPDATE `blog_posts` SET `meta_desc_ar`='24,مارس 2021', `meta_desc_en`='24,March 2021', `excerpt_ar`='24,مارس 2021', `excerpt_en`='24,March 2021', `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='الاحتفال بعشرة آلاف حالة من الولادة بدون ألم', `image_alt_en`='Celebrating ten thousand Moms who enjoyed painless childbirth' WHERE `id`='fe9dba6c-4454-565e-883e-d57ad43de7bf';
UPDATE `blog_posts` SET `meta_desc_ar`='15,أغسطس 2021', `meta_desc_en`='25,August 2021', `excerpt_ar`='15,أغسطس 2021', `excerpt_en`='25,August 2021', `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='الزمالة في أمراض النساء التجميلية، دبي، أغسطس 2021', `image_alt_en`='Fellowship in Aesthetic Gynecology' WHERE `id`='de6446d0-4f1d-5339-bbf6-eb24fd76689d';
UPDATE `blog_posts` SET `meta_desc_ar`='10,أكتوبر 2016', `meta_desc_en`='10,October 2016', `excerpt_ar`='10,أكتوبر 2016', `excerpt_en`='10,October 2016', `tag_ar`='دكتور احمد مرزوق', `tag_en`=NULL, `image_alt_ar`='افتتاح عيادة مدينة نصر', `image_alt_en`='Nasr City Clinic Opening' WHERE `id`='023bae7b-9b4c-55db-b5d6-f3342d73860d';
UPDATE `blog_posts` SET `meta_desc_ar`='07,يونيو 2017', `meta_desc_en`='07,June 2017', `excerpt_ar`='07,يونيو 2017', `excerpt_en`='07,June 2017', `tag_ar`='dr ahmed marzouk', `tag_en`=NULL, `image_alt_ar`='افتتاح فرع التجمع الخامس', `image_alt_en`='Opening of the Fifth Settlement Branch' WHERE `id`='7f128106-d649-501d-8947-239229e63ade';
UPDATE `blog_posts` SET `meta_desc_ar`='قد تحتاجين إلى بعض النصائح قبل عملية الولادة القيصرية والتي سوف تهدئ من روعكِ بلا شك، سوف تجدي كل ما تحتاجين إليه وأكثر في هذا المقال.', `meta_desc_en`=NULL, `excerpt_ar`='قد تحتاجين إلى بعض النصائح قبل عملية الولادة القيصرية والتي سوف تهدئ من روعكِ بلا شك، سوف تجدي كل ما تحتاجين إليه وأكثر في هذا المقال.', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='نصائح قبل عملية الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='d939db12-25b8-5e79-92f3-f5b6ddfef6b8';
UPDATE `blog_posts` SET `meta_desc_ar`='هل يكون علاج الورم الليفي في الرحم سهلًا؟ وكيف يتم علاجه؟ تلك هي أبرز ما يجول بخاطر كل من تصاب بأورام الرحم الليفية، وعن المخاطر الناتجة عن استئصاله، في هذا…', `meta_desc_en`=NULL, `excerpt_ar`='هل يكون علاج الورم الليفي في الرحم سهلًا؟ وكيف يتم علاجه؟ تلك هي أبرز ما يجول بخاطر كل من تصاب بأورام الرحم الليفية، وعن المخاطر الناتجة عن استئصاله، في هذا…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='علاج الورم الليفي في الرحم', `image_alt_en`=NULL WHERE `id`='b828ea52-c4aa-5277-be64-3c8f85e03054';
UPDATE `blog_posts` SET `meta_desc_ar`='مع تأخر سن الزواج لدى الفتيات في الفترات الأخيرة أصبح لدى الكثير منهن مخاوف من عدم قدرتهن على الإنجاب، ومن هنا ظهرت تقنية تجميد البويضات كحل آمن لهذه…', `meta_desc_en`=NULL, `excerpt_ar`='مع تأخر سن الزواج لدى الفتيات في الفترات الأخيرة أصبح لدى الكثير منهن مخاوف من عدم قدرتهن على الإنجاب، ومن هنا ظهرت تقنية تجميد البويضات كحل آمن لهذه…', `excerpt_en`=NULL, `tag_ar`='أضرار تجميد البويضات', `tag_en`=NULL, `image_alt_ar`='تجميد البويضات', `image_alt_en`=NULL WHERE `id`='0726bf7a-c819-5e37-bf9c-448af6e5238c';
UPDATE `blog_posts` SET `meta_desc_ar`='إن الحاجز الرحمي هو عبارة عن طبقة رقيقة من الأنسجة الموجودة في المهبل والتي تفصل بين المهبل والرحم، وهي توجد على طول الرحم وتفصله إلى نصفين نتيجة حدوث عيب…', `meta_desc_en`=NULL, `excerpt_ar`='إن الحاجز الرحمي هو عبارة عن طبقة رقيقة من الأنسجة الموجودة في المهبل والتي تفصل بين المهبل والرحم، وهي توجد على طول الرحم وتفصله إلى نصفين نتيجة حدوث عيب…', `excerpt_en`=NULL, `tag_ar`='أعراض حاجز الرحم', `tag_en`=NULL, `image_alt_ar`='الحاجز الرحمي', `image_alt_en`=NULL WHERE `id`='36707b39-19ae-5848-b868-b1873ad7e79b';
UPDATE `blog_posts` SET `meta_desc_ar`='تبحث الكثير من السيدات عن بعض النصائح بعد عملية الولادة القيصرية، تعرفي على أهمها من المقال التالي.', `meta_desc_en`=NULL, `excerpt_ar`='تبحث الكثير من السيدات عن بعض النصائح بعد عملية الولادة القيصرية، تعرفي على أهمها من المقال التالي.', `excerpt_en`=NULL, `tag_ar`='وجع ووخز بالجانب الأيمن بعد العملية القيصرية', `tag_en`=NULL, `image_alt_ar`='نصائح بعد عملية الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='7002bc53-f260-5fe4-8bf8-35a974682816';
UPDATE `blog_posts` SET `meta_desc_ar`='إن الإصابة بالأورام الليفية من أكثر الأمور الصعبة التي من الممكن أن يصاب بها شخص ما، وخاصةً في حالة الإصابة بالورم الليفي في الثدي أو الورم الليفي في الرحم…', `meta_desc_en`=NULL, `excerpt_ar`='إن الإصابة بالأورام الليفية من أكثر الأمور الصعبة التي من الممكن أن يصاب بها شخص ما، وخاصةً في حالة الإصابة بالورم الليفي في الثدي أو الورم الليفي في الرحم…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='كل ما تريدين معرفته عن الأورام الليفية', `image_alt_en`=NULL WHERE `id`='a8966dbd-d32a-51d7-bb8d-84e667a53752';
UPDATE `blog_posts` SET `meta_desc_ar`='يظل الألم أحد المخاوف الرئيسية التي تعاني منها النساء في عملية الولادة القيصرية إلى جانب خوفهم من التخدير الكلي ومضاعفاته فظهرت الولادة القيصرية بدون ألم…', `meta_desc_en`=NULL, `excerpt_ar`='يظل الألم أحد المخاوف الرئيسية التي تعاني منها النساء في عملية الولادة القيصرية إلى جانب خوفهم من التخدير الكلي ومضاعفاته فظهرت الولادة القيصرية بدون ألم…', `excerpt_en`=NULL, `tag_ar`='تجربتي مع إبرة الظهر للولادة القيصرية', `tag_en`=NULL, `image_alt_ar`='حقنة الظهر في الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='e178550c-d7c4-50cd-89c9-3655b4448a45';
UPDATE `blog_posts` SET `meta_desc_ar`='لا شك أن انسداد قنوات فالوب يؤثر بشكل مباشر على الخصوبة، فمثلما ذكرنا يمنع انسداد القنوات تلاقي البويضات مع الحيوانات المنوية اللازمة لتخصيبها', `meta_desc_en`=NULL, `excerpt_ar`='إن قنوات فالوب هي الرابط الذي يربط المبيض بالرحم، ويعمل على إيصال البويضات الناتجة من المبيض إلى الرحم كل شهر حتى يحدث تخصيب لها، وبالتالي تكوين جنين، وتعتبر…', `excerpt_en`=NULL, `tag_ar`='تجربتي مع انسداد قناة فالوب', `tag_en`=NULL, `image_alt_ar`='انسداد قنوات فالوب', `image_alt_en`=NULL WHERE `id`='67475b9c-0978-53c7-9571-49473ecb9f05';
UPDATE `blog_posts` SET `meta_desc_ar`='تنتشر التهابات المهبل بين عدد كبير من النساء وتختلف في أعراضها من سيدة لأخرى، وتختلف في أعراضها كالحكة والحرقة، والأضرار التي تسببها كتأخر حدوث الحمل', `meta_desc_en`=NULL, `excerpt_ar`='تنتشر الالتهابات المهبلية بين عدد كبير من النساء وتختلف في أعراضها من سيدة لأخرى، وتختلف في أعراضها كالحكة والحرقة، والأضرار التي تسببها كتأخر حدوث الحمل…', `excerpt_en`=NULL, `tag_ar`='علاج التهابات المهبل', `tag_en`=NULL, `image_alt_ar`='علاج التهاب المهبل', `image_alt_en`=NULL WHERE `id`='c8212000-f67e-5e44-a6f9-d1c4df08b9d0';
UPDATE `blog_posts` SET `meta_desc_ar`='قد تحتاج بعض الفتيات اللاتي سوف يقومن بعملية ولادة قيصرية إلى الإجابة على عدد من الأسئلة التي قد تخطر ببالها، تابعي معنا هذا المقال بعنوان أسئلة شائعة بعد…', `meta_desc_en`=NULL, `excerpt_ar`='قد تحتاج بعض الفتيات اللاتي سوف يقومن بعملية ولادة قيصرية إلى الإجابة على عدد من الأسئلة التي قد تخطر ببالها، تابعي معنا هذا المقال بعنوان أسئلة شائعة بعد…', `excerpt_en`=NULL, `tag_ar`='توقف دم النفاس بعد أسبوع من الولادة القيصرية', `tag_en`=NULL, `image_alt_ar`='أسئلة شائعة بعد العملية القيصرية', `image_alt_en`=NULL WHERE `id`='1be32ae3-55b1-571a-8689-600f784c7dc9';
UPDATE `blog_posts` SET `meta_desc_ar`='مع اقتراب موعد العملية القيصرية وأمل أن تكوني أمًا تأتي بعض المخاوف من العملية القيصرية، لذلك إليك أهم التجهيزات قبل الولادة القيصرية التي سوف تحتاجين إليها…', `meta_desc_en`=NULL, `excerpt_ar`='مع اقتراب موعد العملية القيصرية وأمل أن تكوني أمًا تأتي بعض المخاوف من العملية القيصرية، لذلك إليك أهم التجهيزات قبل الولادة القيصرية التي سوف تحتاجين إليها…', `excerpt_en`=NULL, `tag_ar`='قبل العملية القيصرية بيوم', `tag_en`=NULL, `image_alt_ar`='دليلك الشامل قبل عملية الولادة القيصرية بيوم', `image_alt_en`=NULL WHERE `id`='53a11a69-3257-5f26-ae25-72a4d81716e4';
UPDATE `blog_posts` SET `meta_desc_ar`='تعتبر حالة تكيس المبايض حالة شائعة بين الكثير من النساء بعد سن البلوغ، وتحدث نتيجة لاضطراب في الهرمونات التناسلية التي تنتجها المرأة فيحدث زيادة في إنتاج هرمون', `meta_desc_en`=NULL, `excerpt_ar`='تعتبر حالة تكيس المبايض حالة شائعة بين الكثير من النساء بعد سن البلوغ، وتحدث نتيجة لاضطراب في الهرمونات التناسلية التي تنتجها المرأة فيحدث زيادة في إنتاج…', `excerpt_en`=NULL, `tag_ar`='هل يحدث تبويض مع تكيس المبايض', `tag_en`=NULL, `image_alt_ar`='تكيس المبايض', `image_alt_en`=NULL WHERE `id`='7fc1a2bb-332b-52d5-af31-5ee435c390c9';
UPDATE `blog_posts` SET `meta_desc_ar`='هو تحليل لفحص الخصوبة عند الرجل حيث يتم فيه فحص حجم السائل المنوي ولونه وشكل وعدد الحيوانات المنوية وقدرتها على الحركة، إذ أن تحليل السائل المنوي الطبيعي هو…', `meta_desc_en`=NULL, `excerpt_ar`='هو تحليل لفحص الخصوبة عند الرجل حيث يتم فيه فحص حجم السائل المنوي ولونه وشكل وعدد الحيوانات المنوية وقدرتها على الحركة، إذ أن تحليل السائل المنوي الطبيعي هو…', `excerpt_en`=NULL, `tag_ar`='تحليل السائل المنوى للرجل', `tag_en`=NULL, `image_alt_ar`='تحليل السائل المنوي', `image_alt_en`=NULL WHERE `id`='4ee5a60f-d75b-53c8-935c-1765073df51a';
UPDATE `blog_posts` SET `meta_desc_ar`='إن البطن المترهل بعد الولادة القيصرية مزعجة للكثير منا، فهل يوجد حل لها؟ نعم، إن الحل يكمن في عملية شد البطن بعد الولادة القيصرية الذي يحسن من شكل البطن بعد…', `meta_desc_en`=NULL, `excerpt_ar`='إن البطن المترهل بعد الولادة القيصرية مزعجة للكثير منا، فهل يوجد حل لها؟ نعم، إن الحل يكمن في عملية شد البطن بعد الولادة القيصرية الذي يحسن من شكل البطن بعد…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='تجربتي مع شد البطن بعد الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='7ec779f5-0d2d-51c9-b18b-f68ea96c6922';
UPDATE `blog_posts` SET `meta_desc_ar`='يعتبر الحمل بعد الولادة القيصرية مصدر قلق للكثير من الفتيات اللاتي قد خضعن لعملية ولادة قيصرية في السابق، وهل يمكن الولادة بشكل طبيعيي فيما بعد أم أصبحت…', `meta_desc_en`=NULL, `excerpt_ar`='يعتبر الحمل بعد الولادة القيصرية مصدر قلق للكثير من الفتيات اللاتي قد خضعن لعملية ولادة قيصرية في السابق، وهل يمكن الولادة بشكل طبيعيي فيما بعد أم أصبحت…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='الحمل بعد عملية الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='f0837ae0-7862-5f21-b3ad-5f8f768b5ea5';
UPDATE `blog_posts` SET `meta_desc_ar`='انتشرت ظاهرة الإصابة بالأورام الليفية لدى العديد من النساء في الفترة الأخيرة، ومعها زاد القلق عن تأخر الحمل والإنجاب، وماهية علاقة الورم الليفي والحمل…', `meta_desc_en`=NULL, `excerpt_ar`='انتشرت ظاهرة الإصابة بالأورام الليفية لدى العديد من النساء في الفترة الأخيرة، ومعها زاد القلق عن تأخر الحمل والإنجاب، وماهية علاقة الورم الليفي والحمل…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='الورم الليفي والحمل', `image_alt_en`=NULL WHERE `id`='e9a0c89d-b332-5e2c-bace-567e34f1570f';
UPDATE `blog_posts` SET `meta_desc_ar`='انتشرت عمليات الحقن المجهري في الفترة الأخيرة، وبدأنا نسمع عن خضوع كثير من أصحابنا وأقاربنا لها لمساعدتهم على الإنجاب، فما هو الحقن المجهري؟ وكيف تتم تلك…', `meta_desc_en`=NULL, `excerpt_ar`='انتشرت عمليات الحقن المجهري في الفترة الأخيرة، وبدأنا نسمع عن خضوع كثير من أصحابنا وأقاربنا لها لمساعدتهم على الإنجاب، فما هو الحقن المجهري؟ وكيف تتم تلك…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='الحقن المجهري', `image_alt_en`=NULL WHERE `id`='e86db0db-526c-50cd-83ba-8a92b8057677';
UPDATE `blog_posts` SET `meta_desc_ar`='الولادة القيصرية بدون ألم هي أمنية عزيزة لكل أم تحلم بتحقيق حلم الأمومة وحمل مولودها بين يديها، لكنها تخاف من آلام الولادة، ولكن السيدات اللاتي وقع اختيارهن…', `meta_desc_en`=NULL, `excerpt_ar`='الولادة القيصرية بدون ألم هي أمنية عزيزة لكل أم تحلم بتحقيق حلم الأمومة وحمل مولودها بين يديها، لكنها تخاف من آلام الولادة، ولكن السيدات اللاتي وقع اختيارهن…', `excerpt_en`=NULL, `tag_ar`='تجربتي مع التاب بلوك', `tag_en`=NULL, `image_alt_ar`='الولادة بدون ألم تاب بلوك', `image_alt_en`=NULL WHERE `id`='941791c1-7956-51c9-ad73-a8ce1acf60d1';
UPDATE `blog_posts` SET `meta_desc_ar`='تخشى العديد من السيدات من الولادة وخاصةً من الولادة القيصرية، ويظل العديد من السيدات يسألن ويبحثن عن أشهر مخاطر ما بعد الولادة القيصرية، وعن أشهر ما قد يسمعن…', `meta_desc_en`=NULL, `excerpt_ar`='تخشى العديد من السيدات من الولادة وخاصةً من الولادة القيصرية، ويظل العديد من السيدات يسألن ويبحثن عن أشهر مخاطر ما بعد الولادة القيصرية، وعن أشهر ما قد يسمعن…', `excerpt_en`=NULL, `tag_ar`='علاج تحجر الثدي بعد الولادة القيصرية', `tag_en`=NULL, `image_alt_ar`='مخاطر ما بعد الولادة القيصرية', `image_alt_en`=NULL WHERE `id`='855a89c4-9414-5b83-8b5b-4ae18ac7903e';
UPDATE `blog_posts` SET `meta_desc_ar`='قد تكون عملية الحقن المجهري الملجأ للعديد من الأزواج الذين يسعون لحدوث حمل، ومع زيادة التطور العلمي أصبح من الممكن تحديد نوع الجنين في عملية الحقن المجهري…', `meta_desc_en`=NULL, `excerpt_ar`='قد تكون عملية الحقن المجهري الملجأ للعديد من الأزواج الذين يسعون لحدوث حمل، ومع زيادة التطور العلمي أصبح من الممكن تحديد نوع الجنين في عملية الحقن المجهري…', `excerpt_en`=NULL, `tag_ar`=NULL, `tag_en`=NULL, `image_alt_ar`='تحديد نوع الجنين', `image_alt_en`=NULL WHERE `id`='7dd3709a-686a-5e53-b3f5-1efb6ffb1aed';
COMMIT;
