-- Recovery: add + populate blog focus-keyword fields from PROVEN Search Console
-- queries (stable pre-migration window) — recovers the exact terms each page ranked for.
-- Idempotent (MariaDB). Safe to re-run.
ALTER TABLE `blog_posts` ADD COLUMN IF NOT EXISTS `keywords_ar` TEXT NULL, ADD COLUMN IF NOT EXISTS `keywords_en` TEXT NULL;
START TRANSACTION;
UPDATE `blog_posts` SET `keywords_ar`='علاج التهابات المهبل, علاج التهابات المهبل للمتزوجات, التهابات المهبل, علاج الالتهابات المهبلية, علاج حرقان المهبل', `keywords_en`='vaginal infection treatment, treatment of vaginal infections, vaginal itching and burning, vaginal infection for married women' WHERE `id`='c8212000-f67e-5e44-a6f9-d1c4df08b9d0';
UPDATE `blog_posts` SET `keywords_ar`='تاب بلوك, ابرة تاب بلوك, سعر حقنة التاب بلوك, تجربتي مع التاب بلوك, الولادة بدون ألم', `keywords_en`='TAP block, TAP block injection, painless cesarean, painless delivery' WHERE `id`='941791c1-7956-51c9-ad73-a8ce1acf60d1';
UPDATE `blog_posts` SET `keywords_ar`='الحمل الكيميائي, ما هو الحمل الكيميائي, اعراض الحمل الكيميائي, اسباب الحمل الكيميائي', `keywords_en`='chemical pregnancy, what is a chemical pregnancy, chemical pregnancy symptoms, chemical pregnancy causes' WHERE `id`='3440ab6d-44b5-5b8c-8573-3de70f652db3';
UPDATE `blog_posts` SET `keywords_ar`='نصائح بعد الولادة القيصرية, طريقة النوم بعد الولادة القيصرية, متى الاستحمام بعد الولادة القيصرية, الأشياء الممنوعة بعد العملية القيصرية', `keywords_en`='tips after cesarean delivery, sleeping after a c-section, bathing after cesarean, things to avoid after c-section' WHERE `id`='7002bc53-f260-5fe4-8bf8-35a974682816';
UPDATE `blog_posts` SET `keywords_ar`='حقنة الظهر في الولادة القيصرية, حقنة الابيديورال, البنج النصفي للولادة القيصرية, إبرة الظهر للولادة القيصرية', `keywords_en`='epidural for cesarean, epidural injection, spinal anesthesia c-section, back injection for delivery' WHERE `id`='e178550c-d7c4-50cd-89c9-3655b4448a45';
UPDATE `blog_posts` SET `keywords_ar`='تحليل السائل المنوي, تحليل السائل المنوي للرجل, كيفية عمل تحليل السائل المنوي, تحليل السائل المنوي الطبيعي', `keywords_en`='semen analysis, semen analysis for men, how semen analysis is done, normal semen analysis' WHERE `id`='4ee5a60f-d75b-53c8-935c-1765073df51a';
UPDATE `blog_posts` SET `keywords_ar`='دم النفاس بعد الولادة القيصرية, متى يتوقف دم النفاس بعد العملية القيصرية, الدورة الشهرية بعد الولادة القيصرية, أسئلة بعد العملية القيصرية', `keywords_en`='postpartum bleeding after cesarean, when postpartum bleeding stops, period after c-section, common questions after cesarean' WHERE `id`='1be32ae3-55b1-571a-8689-600f784c7dc9';
UPDATE `blog_posts` SET `keywords_ar`='علاج القيء المستعصي في الحمل, أسباب القيء المستعصي للحامل, علاج الترجيع للحامل, القيء أثناء الحمل', `keywords_en`='intractable vomiting in pregnancy, causes of severe vomiting in pregnancy, treating vomiting for pregnant women, morning sickness' WHERE `id`='4ac6c686-9367-504b-8281-8e79598b61b3';
UPDATE `blog_posts` SET `keywords_ar`='انسداد قناة فالوب, أفضل علاج لانسداد قناة فالوب, علاج انسداد قناة فالوب, تجربتي مع انسداد قناة فالوب', `keywords_en`='fallopian tube blockage, best treatment for blocked fallopian tube, treating tubal blockage, my experience with blocked tubes' WHERE `id`='67475b9c-0978-53c7-9571-49473ecb9f05';
UPDATE `blog_posts` SET `keywords_ar`='قبل العملية القيصرية بيوم, الصيام قبل القيصرية, التحاليل اللازمة قبل الولادة القيصرية, هل شرب الماء قبل الولادة القيصرية مضر', `keywords_en`='the day before a cesarean, fasting before cesarean, tests before cesarean, drinking water before c-section' WHERE `id`='53a11a69-3257-5f26-ae25-72a4d81716e4';
UPDATE `blog_posts` SET `keywords_ar`='حمى النفاس, اعراض حمى النفاس, علاج حمى النفاس, الحمى بعد الولادة', `keywords_en`='puerperal fever, postpartum fever symptoms, treating puerperal fever, fever after delivery' WHERE `id`='c82fe0e4-efab-589c-b855-a841c7313ae8';
UPDATE `blog_posts` SET `keywords_ar`='تجميد البويضات, أضرار تجميد البويضات, كيف يتم تجميد البويضات, تجميد البويضات في سن الأربعين', `keywords_en`='egg freezing, egg freezing risks, how egg freezing is done, egg freezing at 40' WHERE `id`='0726bf7a-c819-5e37-bf9c-448af6e5238c';
UPDATE `blog_posts` SET `keywords_ar`='مخاطر ما بعد الولادة القيصرية, علامات الخطر بعد الولادة القيصرية, اعراض ما بعد الولادة القيصرية', `keywords_en`='risks after cesarean delivery, danger signs after c-section, symptoms after cesarean' WHERE `id`='855a89c4-9414-5b83-8b5b-4ae18ac7903e';
UPDATE `blog_posts` SET `keywords_ar`='الحاجز الرحمي, ما هو الحاجز الرحمي, أعراض حاجز الرحم, حاجز الرحم', `keywords_en`='uterine septum, what is a uterine septum, septate uterus symptoms, uterine septum' WHERE `id`='36707b39-19ae-5848-b868-b1873ad7e79b';
UPDATE `blog_posts` SET `keywords_ar`='التهاب الثدي, هل التهاب الثدي خطير, علاج التهاب الثدي, التهاب الثدي عند المرضع', `keywords_en`='mastitis, is mastitis dangerous, mastitis treatment, mastitis while breastfeeding' WHERE `id`='96dd8880-1d95-52c2-b0c5-af844faab788';
UPDATE `blog_posts` SET `keywords_ar`='تكيس المبايض, اعراض تكيس المبايض, علاج تكيس المبايض, متلازمة تكيس المبايض', `keywords_en`='PCOS, PCOS symptoms, PCOS treatment, polycystic ovary syndrome' WHERE `id`='7fc1a2bb-332b-52d5-af31-5ee435c390c9';
UPDATE `blog_posts` SET `keywords_ar`='الورم الليفي والحمل, الورم الليفي أثناء الحمل, تأثير الورم الليفي على الحمل', `keywords_en`='fibroids and pregnancy, fibroids during pregnancy, effect of fibroids on pregnancy' WHERE `id`='e9a0c89d-b332-5e2c-bace-567e34f1570f';
UPDATE `blog_posts` SET `keywords_ar`='الحقن المجهري, خطوات الحقن المجهري, نسبة نجاح الحقن المجهري', `keywords_en`='ICSI, ICSI steps, ICSI success rate, intracytoplasmic sperm injection' WHERE `id`='e86db0db-526c-50cd-83ba-8a92b8057677';
UPDATE `blog_posts` SET `keywords_ar`='تحديد نوع الجنين, تحديد جنس الجنين, تحديد نوع الجنين بالحقن المجهري', `keywords_en`='gender selection, sex selection, gender selection with ICSI' WHERE `id`='7dd3709a-686a-5e53-b3f5-1efb6ffb1aed';
UPDATE `blog_posts` SET `keywords_ar`='علاج الورم الليفي في الرحم, استئصال الورم الليفي, الورم الليفي في الرحم, الحمل بعد استئصال الورم الليفي', `keywords_en`='uterine fibroid treatment, fibroid removal, uterine fibroids, pregnancy after fibroid removal' WHERE `id`='b828ea52-c4aa-5277-be64-3c8f85e03054';
UPDATE `blog_posts` SET `keywords_ar`='الأورام الليفية, اعراض الورم الليفي, علاج الأورام الليفية, أنواع الأورام الليفية', `keywords_en`='uterine fibroids, fibroid symptoms, fibroid treatment, types of fibroids' WHERE `id`='a8966dbd-d32a-51d7-bb8d-84e667a53752';
UPDATE `blog_posts` SET `keywords_ar`='الحمل بعد الولادة القيصرية, متى يحدث الحمل بعد القيصرية, الحمل بعد القيصرية بشهرين', `keywords_en`='pregnancy after cesarean, when pregnancy happens after c-section, getting pregnant after cesarean' WHERE `id`='f0837ae0-7862-5f21-b3ad-5f8f768b5ea5';
UPDATE `blog_posts` SET `keywords_ar`='شد البطن بعد الولادة القيصرية, تجربتي مع شد البطن بعد القيصرية, عملية شد البطن بعد الولادة', `keywords_en`='tummy tuck after cesarean, my tummy tuck after c-section experience, abdominoplasty after delivery' WHERE `id`='7ec779f5-0d2d-51c9-b18b-f68ea96c6922';
UPDATE `blog_posts` SET `keywords_ar`='انقطاع الطمث, اعراض انقطاع الطمث, سن اليأس, علاج انقطاع الطمث', `keywords_en`='menopause, menopause symptoms, treating menopause, perimenopause' WHERE `id`='0e1eb956-fd14-56f0-9fca-d851b00d6ff8';
UPDATE `blog_posts` SET `keywords_ar`='دكتور احمد مرزوق, الولادة بدون ألم', `keywords_en`='Dr. Ahmed Marzouk, painless delivery' WHERE `id`='fe9dba6c-4454-565e-883e-d57ad43de7bf';
UPDATE `blog_posts` SET `keywords_ar`='دكتور احمد مرزوق, دكتور احمد مرزوق نساء وتوليد', `keywords_en`='Dr. Ahmed Marzouk, Dr. Ahmed Marzouk OB-GYN' WHERE `id`='023bae7b-9b4c-55db-b5d6-f3342d73860d';
UPDATE `blog_posts` SET `keywords_ar`='دكتور احمد مرزوق, دكتور احمد مرزوق نساء وتوليد, عيادة التجمع الخامس', `keywords_en`='Dr. Ahmed Marzouk, Dr. Ahmed Marzouk OB-GYN, Fifth Settlement clinic' WHERE `id`='7f128106-d649-501d-8947-239229e63ade';
UPDATE `blog_posts` SET `keywords_ar`='تسمم الحمل, ارتفاع ضغط الدم والحمل, اعراض تسمم الحمل, ارتفاع ضغط الدم أثناء الحمل', `keywords_en`='preeclampsia, high blood pressure in pregnancy, preeclampsia symptoms, gestational hypertension' WHERE `id`='a7eef3d3-024e-5baf-8927-767d329a4573';
UPDATE `blog_posts` SET `keywords_ar`='دكتور احمد مرزوق, أمراض النساء التجميلية, الزمالة في أمراض النساء التجميلية', `keywords_en`='Dr. Ahmed Marzouk, cosmetic gynecology, fellowship in cosmetic gynecology' WHERE `id`='de6446d0-4f1d-5339-bbf6-eb24fd76689d';
UPDATE `blog_posts` SET `keywords_ar`='نصائح قبل الولادة القيصرية, التحضير للولادة القيصرية, خطوات الولادة القيصرية, عدد الولادات القيصرية المسموح بها', `keywords_en`='tips before cesarean delivery, preparing for a c-section, cesarean steps, how many c-sections are allowed' WHERE `id`='d939db12-25b8-5e79-92f3-f5b6ddfef6b8';
COMMIT;
